import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#3e484f',
        'on-tertiary-fixed': '#131d23',
        'on-primary': '#2a3400',
        'on-primary-fixed-variant': '#3e4c00',
        'steel-bright': '#E2E8F0',
        'surface-container-low': '#191c1f',
        'inverse-surface': '#e1e2e7',
        'on-secondary-fixed-variant': '#41474e',
        'telemetry-active': '#D4FF00',
        'tertiary-fixed-dim': '#bec8d0',
        'on-tertiary-container': '#5c666d',
        'surface-dim': '#111417',
        'surface-container-high': '#272a2d',
        'on-secondary': '#2b3137',
        'on-surface': '#e1e2e7',
        'inverse-on-surface': '#2e3134',
        destructive: '#FF3B30',
        'on-primary-container': '#596c00',
        'on-primary-fixed': '#171e00',
        'surface-container': '#1d2023',
        'inverse-primary': '#536600',
        secondary: '#c1c7cf',
        'primary-fixed-dim': '#b0d500',
        'on-error-container': '#ffdad6',
        surface: '#111417',
        'on-secondary-container': '#afb6bd',
        'signal-volt-hover': '#CCFF00',
        'surface-overlay': '#181C20',
        'on-secondary-fixed': '#161c22',
        'surface-container-lowest': '#0b0e11',
        tertiary: '#ffffff',
        'outline-variant': '#444932',
        'surface-highlight': '#22272E',
        'surface-bright': '#37393d',
        'tertiary-container': '#dae4ec',
        background: '#0B0E11',
        'surface-base': '#0B0E11',
        'surface-variant': '#323538',
        'surface-tint': '#b0d500',
        'signal-volt-glow': '#D4FF001A',
        'secondary-fixed': '#dde3eb',
        'on-background': '#e1e2e7',
        primary: '#ffffff',
        'primary-container': '#caf300',
        'on-tertiary': '#283238',
        'on-error': '#690005',
        outline: '#8f9378',
        'secondary-container': '#41474e',
        'primary-fixed': '#caf300',
        'surface-container-highest': '#323538',
        'surface-raised': '#121518',
        'secondary-fixed-dim': '#c1c7cf',
        'on-surface-variant': '#c5c9ac',
        'steel-muted': '#8E98A0',
        'signal-volt': '#D4FF00',
        'tertiary-fixed': '#dae4ec',
        error: '#ffb4ab',
        'error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-lg': '4rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        'space-xs': '0.25rem',
        gutter: '1.5rem',
        'margin-sm': '1rem',
        'gutter-sm': '1rem',
        'space-sm': '0.5rem',
        margin: '2rem',
        'space-md': '1rem',
      },
      scale: {
        '102': '1.02',
      },
      fontFamily: {
        'headline-xl': ['Anton', 'sans-serif'],
        'metric-huge': ['Anton', 'sans-serif'],
        'headline-lg-mobile': ['Anton', 'sans-serif'],
        'body-lg': ['Space Grotesk', 'sans-serif'],
        'headline-xl-mobile': ['Anton', 'sans-serif'],
        'headline-md': ['Anton', 'sans-serif'],
        'metric-huge-mobile': ['Anton', 'sans-serif'],
        'title-md': ['Space Grotesk', 'sans-serif'],
        'body-md': ['Space Grotesk', 'sans-serif'],
        'body-sm': ['Space Grotesk', 'sans-serif'],
        'display-hero': ['Anton', 'sans-serif'],
        'title-lg': ['Space Grotesk', 'sans-serif'],
        'label-telemetry': ['Space Grotesk', 'sans-serif'],
        'headline-lg': ['Anton', 'sans-serif'],
        'display-hero-mobile': ['Anton', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['56px', { lineHeight: '60px', letterSpacing: '0.02em', fontWeight: '400' }],
        'metric-huge': ['72px', { lineHeight: '72px', letterSpacing: '0.01em', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', letterSpacing: '0.03em', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-xl-mobile': ['36px', { lineHeight: '40px', letterSpacing: '0.02em', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '30px', letterSpacing: '0.03em', fontWeight: '400' }],
        'metric-huge-mobile': ['44px', { lineHeight: '48px', letterSpacing: '0.01em', fontWeight: '400' }],
        'title-md': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '600' }],
        'body-md': ['15px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '400' }],
        'display-hero': ['80px', { lineHeight: '84px', letterSpacing: '0.02em', fontWeight: '400' }],
        'title-lg': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-telemetry': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '700' }],
        'headline-lg': ['36px', { lineHeight: '42px', letterSpacing: '0.03em', fontWeight: '400' }],
        'display-hero-mobile': ['48px', { lineHeight: '52px', letterSpacing: '0.02em', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};

export default config;
