/**
 * Canonical exercise catalogue seed (Day 2).
 * Substitutions reference other entries by `slug` and are resolved to ObjectIds after insert.
 */
function slugify(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

const EXERCISE_SEED = [
  // —— Chest ——
  {
    name: 'Barbell Bench Press',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front_delts'],
    movementPattern: 'horizontal_press',
    equipmentRequired: ['barbell', 'bench'],
    difficulty: 'intermediate',
    type: 'compound',
    instructions: 'Lie on a flat bench, unrack the bar, lower to mid-chest, press to lockout.',
    formCues: ['retract scapulae', 'feet planted', 'bar path slightly diagonal'],
    contraindications: ['acute shoulder impingement', 'fresh pec strain'],
    substitutionSlugs: ['dumbbell-bench-press', 'machine-chest-press'],
  },
  {
    name: 'Dumbbell Bench Press',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front_delts'],
    movementPattern: 'horizontal_press',
    equipmentRequired: ['dumbbell', 'bench'],
    difficulty: 'beginner',
    type: 'compound',
    instructions: 'Press dumbbells from chest height to full extension while keeping wrists stacked.',
    formCues: ['neutral wrists', 'soft lockout', 'control the eccentric'],
    contraindications: ['acute shoulder pain'],
    substitutionSlugs: ['barbell-bench-press', 'push-up'],
  },
  {
    name: 'Incline Dumbbell Press',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts', 'triceps'],
    movementPattern: 'incline_press',
    equipmentRequired: ['dumbbell', 'bench'],
    difficulty: 'intermediate',
    type: 'compound',
    instructions: 'Set bench 30–45°, press dumbbells up and slightly together.',
    formCues: ['ribs down', 'do not flare elbows past 75°'],
    contraindications: ['anterior shoulder irritation'],
    substitutionSlugs: ['incline-barbell-press', 'machine-chest-press'],
  },
  {
    name: 'Incline Barbell Press',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts', 'triceps'],
    movementPattern: 'incline_press',
    equipmentRequired: ['barbell', 'bench'],
    difficulty: 'intermediate',
    type: 'compound',
    instructions: 'Press from an incline bench, lowering the bar to the upper chest.',
    formCues: ['stable scapulae', 'controlled touch'],
    contraindications: ['shoulder impingement'],
    substitutionSlugs: ['incline-dumbbell-press'],
  },
  {
    name: 'Machine Chest Press',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front_delts'],
    movementPattern: 'horizontal_press',
    equipmentRequired: ['machine'],
    difficulty: 'beginner',
    type: 'compound',
    instructions: 'Sit tall, grip handles at chest height, press until elbows nearly lock.',
    formCues: ['seat height so handles align with mid-chest', 'smooth tempo'],
    contraindications: [],
    substitutionSlugs: ['dumbbell-bench-press', 'push-up'],
  },
  {
    name: 'Cable Fly',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts'],
    movementPattern: 'horizontal_fly',
    equipmentRequired: ['cable_machine'],
    difficulty: 'beginner',
    type: 'isolation',
    instructions: 'With cables at shoulder height, bring handles together in a wide arc.',
    formCues: ['slight elbow bend', 'squeeze at midline', 'do not shrug'],
    contraindications: ['pec tendinopathy flare'],
    substitutionSlugs: ['dumbbell-fly', 'pec-deck'],
  },
  {
    name: 'Dumbbell Fly',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts'],
    movementPattern: 'horizontal_fly',
    equipmentRequired: ['dumbbell', 'bench'],
    difficulty: 'intermediate',
    type: 'isolation',
    instructions: 'Lower dumbbells in a wide arc until stretch is felt, then squeeze up.',
    formCues: ['soft elbows', 'stop before shoulder stress'],
    contraindications: ['shoulder instability'],
    substitutionSlugs: ['cable-fly', 'pec-deck'],
  },
  {
    name: 'Pec Deck',
    primaryMuscles: ['chest'],
    secondaryMuscles: [],
    movementPattern: 'horizontal_fly',
    equipmentRequired: ['machine'],
    difficulty: 'beginner',
    type: 'isolation',
    instructions: 'Bring the pads together in front of the chest with a controlled squeeze.',
    formCues: ['shoulders down', 'pause briefly at peak'],
    contraindications: [],
    substitutionSlugs: ['cable-fly'],
  },
  {
    name: 'Push-Up',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front_delts', 'core'],
    movementPattern: 'horizontal_press',
    equipmentRequired: ['bodyweight'],
    difficulty: 'beginner',
    type: 'compound',
    instructions: 'From a high plank, lower chest toward the floor and press back up.',
    formCues: ['body in a straight line', 'elbows ~45°'],
    contraindications: ['acute wrist pain'],
    substitutionSlugs: ['dumbbell-bench-press', 'machine-chest-press'],
  },

  // —— Back ——
  {
    name: 'Conventional Deadlift',
    primaryMuscles: ['back', 'glutes', 'hamstrings'],
    secondaryMuscles: ['core', 'forearms', 'traps'],
    movementPattern: 'hinge',
    equipmentRequired: ['barbell'],
    difficulty: 'advanced',
    type: 'compound',
    instructions: 'Hinge, grip the bar, brace, and stand tall by driving through the floor.',
    formCues: ['neutral spine', 'bar close to shins', 'lats engaged'],
    contraindications: ['acute low-back pain', 'uncontrolled hypertension'],
    substitutionSlugs: ['romanian-deadlift', 'trap-bar-deadlift'],
  },
  {
    name: 'Romanian Deadlift',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['back', 'core'],
    movementPattern: 'hinge',
    equipmentRequired: ['barbell'],
    difficulty: 'intermediate',
    type: 'compound',
    instructions: 'From standing, push hips back while keeping a soft knee bend until hamstrings stretch.',
    formCues: ['bar against thighs', 'hips back', 'chest proud'],
    contraindications: ['acute low-back flare'],
    substitutionSlugs: ['dumbbell-rdl', 'good-morning'],
  },
  {
    name: 'Dumbbell RDL',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['back'],
    movementPattern: 'hinge',
    equipmentRequired: ['dumbbell'],
    difficulty: 'beginner',
    type: 'compound',
    instructions: 'Hold dumbbells at the sides and hinge until a strong hamstring stretch.',
    formCues: ['soft knees', 'neutral neck'],
    contraindications: [],
    substitutionSlugs: ['romanian-deadlift', 'kettlebell-swing'],
  },
  {
    name: 'Trap Bar Deadlift',
    primaryMuscles: ['glutes', 'quads', 'back'],
    secondaryMuscles: ['hamstrings', 'core'],
    movementPattern: 'hinge',
    equipmentRequired: ['barbell'],
    difficulty: 'intermediate',
    type: 'compound',
    instructions: 'Stand inside the trap bar, grip handles, stand tall with a braced trunk.',
    formCues: ['sit between handles', 'drive floor away'],
    contraindications: ['acute low-back pain'],
    substitutionSlugs: ['conventional-deadlift', 'goblet-squat'],
  },
  {
    name: 'Barbell Bent-Over Row',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'rear_delts'],
    movementPattern: 'horizontal_pull',
    equipmentRequired: ['barbell'],
    difficulty: 'intermediate',
    type: 'compound',
    instructions: 'Hinge to ~45°, row the bar to the lower ribs, then lower with control.',
    formCues: ['torso still', 'elbows tucked', 'squeeze mid-back'],
    contraindications: ['acute low-back pain'],
    substitutionSlugs: ['chest-supported-dumbbell-row', 'seated-cable-row'],
  },
  {
    name: 'Chest-Supported Dumbbell Row',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'rear_delts'],
    movementPattern: 'horizontal_pull',
    equipmentRequired: ['dumbbell', 'bench'],
    difficulty: 'beginner',
    type: 'compound',
    instructions: 'Lie chest-down on an incline bench and row dumbbells toward the hips.',
    formCues: ['pull elbows back', 'avoid shrugging'],
    contraindications: [],
    substitutionSlugs: ['seated-cable-row', 'barbell-bent-over-row'],
  },
  {
    name: 'Seated Cable Row',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'rear_delts'],
    movementPattern: 'horizontal_pull',
    equipmentRequired: ['cable_machine'],
    difficulty: 'beginner',
    type: 'compound',
    instructions: 'Sit tall, pull the handle to the torso, then extend arms under control.',
    formCues: ['ribs down', 'shoulder blades squeeze'],
    contraindications: [],
    substitutionSlugs: ['chest-supported-dumbbell-row'],
  },
  {
    name: 'Lat Pulldown',
    primaryMuscles: ['lats', 'back'],
    secondaryMuscles: ['biceps'],
    movementPattern: 'vertical_pull',
    equipmentRequired: ['cable_machine', 'machine'],
    difficulty: 'beginner',
    type: 'compound',
    instructions: 'Pull the bar to the upper chest while leaning slightly back.',
    formCues: ['depress scapulae first', 'elbows down and back'],
    contraindications: [],
    substitutionSlugs: ['pull-up', 'assisted-pull-up'],
  },
  {
    name: 'Pull-Up',
    primaryMuscles: ['lats', 'back'],
    secondaryMuscles: ['biceps', 'core'],
    movementPattern: 'vertical_pull',
    equipmentRequired: ['pull_up_bar'],
    difficulty: 'advanced',
    type: 'compound',
    instructions: 'Hang from the bar and pull until the chin clears, then lower fully.',
    formCues: ['full hang start', 'avoid kipping unless programmed'],
    contraindications: ['acute shoulder pain', 'elbow tendinopathy flare'],
    substitutionSlugs: ['lat-pulldown', 'assisted-pull-up'],
  },
  {
    name: 'Assisted Pull-Up',
    primaryMuscles: ['lats', 'back'],
    secondaryMuscles: ['biceps'],
    movementPattern: 'vertical_pull',
    equipmentRequired: ['machine', 'pull_up_bar'],
    difficulty: 'beginner',
    type: 'compound',
    instructions: 'Use assistance so you can complete full-range pull-ups with control.',
    formCues: ['same scapular pattern as a free pull-up'],
    contraindications: [],
    substitutionSlugs: ['lat-pulldown', 'pull-up'],
  },
  {
    name: 'Single-Arm Dumbbell Row',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    movementPattern: 'horizontal_pull',
    equipmentRequired: ['dumbbell', 'bench'],
    difficulty: 'beginner',
    type: 'compound',
    instructions: 'Support one knee/hand on a bench and row the dumbbell to the hip.',
    formCues: ['square hips', 'elbow past torso'],
    contraindications: [],
    substitutionSlugs: ['chest-supported-dumbbell-row', 'seated-cable-row'],
  },
  {
    name: 'Face Pull',
    primaryMuscles: ['rear_delts', 'upper_back'],
    secondaryMuscles: ['rotator_cuff'],
    movementPattern: 'horizontal_pull',
    equipmentRequired: ['cable_machine', 'resistance_bands'],
    difficulty: 'beginner',
    type: 'isolation',
    instructions: 'Pull a rope to the face, externally rotating at the end range.',
    formCues: ['elbows high', 'thumbs back'],
    contraindications: [],
    substitutionSlugs: ['band-pull-apart'],
  },
  {
    name: 'Band Pull-Apart',
    primaryMuscles: ['rear_delts', 'upper_back'],
    secondaryMuscles: [],
    movementPattern: 'horizontal_pull',
    equipmentRequired: ['resistance_bands'],
    difficulty: 'beginner',
    type: 'isolation',
    instructions: 'Hold a band at shoulder height and pull it apart until hands are wide.',
    formCues: ['soft elbows', 'squeeze shoulder blades'],
    contraindications: [],
    substitutionSlugs: ['face-pull'],
  },

  // —— Legs ——
  {
    name: 'Back Squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core', 'hamstrings'],
    movementPattern: 'squat',
    equipmentRequired: ['barbell'],
    difficulty: 'intermediate',
    type: 'compound',
    instructions: 'Bar on upper back, sit between the hips, stand by driving through mid-foot.',
    formCues: ['brace before descent', 'knees track toes', 'depth as mobility allows'],
    contraindications: ['acute knee flare', 'uncontrolled low-back pain'],
    substitutionSlugs: ['goblet-squat', 'leg-press'],
  },
  {
    name: 'Front Squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core'],
    movementPattern: 'squat',
    equipmentRequired: ['barbell'],
    difficulty: 'advanced',
    type: 'compound',
    instructions: 'Hold the bar in a front rack and squat while keeping an upright torso.',
    formCues: ['elbows high', 'heels down'],
    contraindications: ['wrist mobility limits', 'acute knee pain'],
    substitutionSlugs: ['goblet-squat', 'hack-squat'],
  },
  {
    name: 'Goblet Squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core'],
    movementPattern: 'squat',
    equipmentRequired: ['dumbbell', 'kettlebell'],
    difficulty: 'beginner',
    type: 'compound',
    instructions: 'Hold a weight at the chest and squat between the heels.',
    formCues: ['elbows inside knees', 'chest tall'],
    contraindications: [],
    substitutionSlugs: ['back-squat', 'leg-press'],
  },
  {
    name: 'Leg Press',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    movementPattern: 'squat',
    equipmentRequired: ['machine'],
    difficulty: 'beginner',
    type: 'compound',
    instructions: 'Press the sled through a controlled range without locking the knees hard.',
    formCues: ['low back glued to pad', 'full foot contact'],
    contraindications: ['acute knee flare'],
    substitutionSlugs: ['goblet-squat', 'hack-squat'],
  },
  {
    name: 'Hack Squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: [],
    movementPattern: 'squat',
    equipmentRequired: ['machine'],
    difficulty: 'intermediate',
    type: 'compound',
    instructions: 'Descend in the hack squat machine until thighs are near parallel, then drive up.',
    formCues: ['knees track toes', 'controlled depth'],
    contraindications: ['patellar pain flare'],
    substitutionSlugs: ['leg-press', 'goblet-squat'],
  },
  {
    name: 'Bulgarian Split Squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core'],
    movementPattern: 'lunge',
    equipmentRequired: ['dumbbell', 'bench'],
    difficulty: 'intermediate',
    type: 'compound',
    instructions: 'Rear foot elevated on a bench; lower until the front thigh is near parallel.',
    formCues: ['torso slight lean', 'front shin mostly vertical'],
    contraindications: ['acute knee pain'],
    substitutionSlugs: ['walking-lunge', 'goblet-squat'],
  },
  {
    name: 'Walking Lunge',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    movementPattern: 'lunge',
    equipmentRequired: ['dumbbell', 'bodyweight'],
    difficulty: 'beginner',
    type: 'compound',
    instructions: 'Step forward into a lunge, then push into the next step continuously.',
    formCues: ['short steps if knees hurt', 'torso upright'],
    contraindications: ['balance disorders', 'acute knee flare'],
    substitutionSlugs: ['bulgarian-split-squat', 'leg-press'],
  },
  {
    name: 'Leg Curl',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: [],
    movementPattern: 'knee_flexion',
    equipmentRequired: ['machine'],
    difficulty: 'beginner',
    type: 'isolation',
    instructions: 'Curl the pad toward the glutes, then lower under control.',
    formCues: ['hips glued down', 'full stretch at bottom'],
    contraindications: [],
    substitutionSlugs: ['romanian-deadlift', 'dumbbell-rdl'],
  },
  {
    name: 'Leg Extension',
    primaryMuscles: ['quads'],
    secondaryMuscles: [],
    movementPattern: 'knee_extension',
    equipmentRequired: ['machine'],
    difficulty: 'beginner',
    type: 'isolation',
    instructions: 'Extend the knees against the pad and pause briefly at the top.',
    formCues: ['do not slam lockout', 'control the eccentric'],
    contraindications: ['acute anterior knee pain'],
    substitutionSlugs: ['goblet-squat', 'leg-press'],
  },
  {
    name: 'Standing Calf Raise',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    movementPattern: 'plantarflexion',
    equipmentRequired: ['machine', 'bodyweight'],
    difficulty: 'beginner',
    type: 'isolation',
    instructions: 'Rise onto the forefoot through a full range, then lower into a stretch.',
    formCues: ['knees soft', 'pause at top'],
    contraindications: ['achilles flare'],
    substitutionSlugs: ['seated-calf-raise'],
  },
  {
    name: 'Seated Calf Raise',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    movementPattern: 'plantarflexion',
    equipmentRequired: ['machine'],
    difficulty: 'beginner',
    type: 'isolation',
    instructions: 'With knees bent, raise the heels and lower into a deep stretch.',
    formCues: ['full ROM', 'no bouncing'],
    contraindications: [],
    substitutionSlugs: ['standing-calf-raise'],
  },
  {
    name: 'Hip Thrust',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    movementPattern: 'hip_extension',
    equipmentRequired: ['barbell', 'bench'],
    difficulty: 'intermediate',
    type: 'compound',
    instructions: 'Upper back on a bench, drive hips up until torso is parallel to the floor.',
    formCues: ['chin tucked', 'posterior pelvic tilt at lockout'],
    contraindications: [],
    substitutionSlugs: ['glute-bridge', 'romanian-deadlift'],
  },
  {
    name: 'Glute Bridge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    movementPattern: 'hip_extension',
    equipmentRequired: ['bodyweight'],
    difficulty: 'beginner',
    type: 'isolation',
    instructions: 'Lie on your back and drive hips up, squeezing the glutes at the top.',
    formCues: ['ribs down', 'push through heels'],
    contraindications: [],
    substitutionSlugs: ['hip-thrust'],
  },
  {
    name: 'Kettlebell Swing',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['back', 'core'],
    movementPattern: 'hinge',
    equipmentRequired: ['kettlebell'],
    difficulty: 'intermediate',
    type: 'compound',
    instructions: 'Hinge and snap the hips to swing the kettlebell to about chest height.',
    formCues: ['hinge not squat', 'arms relaxed'],
    contraindications: ['acute low-back pain'],
    substitutionSlugs: ['dumbbell-rdl', 'romanian-deadlift'],
  },

  // —— Shoulders ——
  {
    name: 'Overhead Press',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'upper_chest', 'core'],
    movementPattern: 'vertical_press',
    equipmentRequired: ['barbell'],
    difficulty: 'intermediate',
    type: 'compound',
    instructions: 'Press the bar from the front rack to lockout overhead, then lower to the shoulders.',
    formCues: ['glutes tight', 'head through at the top'],
    contraindications: ['shoulder impingement', 'uncontrolled hypertension'],
    substitutionSlugs: ['dumbbell-shoulder-press', 'landmine-press'],
  },
  {
    name: 'Dumbbell Shoulder Press',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    movementPattern: 'vertical_press',
    equipmentRequired: ['dumbbell'],
    difficulty: 'beginner',
    type: 'compound',
    instructions: 'Press dumbbells from ear height to overhead without excessive arching.',
    formCues: ['ribs down', 'wrists stacked'],
    contraindications: ['shoulder pain overhead'],
    substitutionSlugs: ['landmine-press', 'machine-shoulder-press'],
  },
  {
    name: 'Machine Shoulder Press',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    movementPattern: 'vertical_press',
    equipmentRequired: ['machine'],
    difficulty: 'beginner',
    type: 'compound',
    instructions: 'Press the machine handles overhead on a fixed path.',
    formCues: ['seat height so handles start near ear level'],
    contraindications: [],
    substitutionSlugs: ['dumbbell-shoulder-press'],
  },
  {
    name: 'Landmine Press',
    primaryMuscles: ['shoulders', 'chest'],
    secondaryMuscles: ['triceps', 'core'],
    movementPattern: 'vertical_press',
    equipmentRequired: ['barbell'],
    difficulty: 'beginner',
    type: 'compound',
    instructions: 'Press one end of a landmine/barbell up and forward from shoulder height.',
    formCues: ['stagger stance', 'finish with reach'],
    contraindications: [],
    substitutionSlugs: ['dumbbell-shoulder-press', 'overhead-press'],
  },
  {
    name: 'Lateral Raise',
    primaryMuscles: ['side_delts'],
    secondaryMuscles: [],
    movementPattern: 'abduction',
    equipmentRequired: ['dumbbell'],
    difficulty: 'beginner',
    type: 'isolation',
    instructions: 'Raise dumbbells out to the sides until roughly shoulder height.',
    formCues: ['soft elbows', 'lead with elbows', 'no swinging'],
    contraindications: ['acute shoulder bursitis'],
    substitutionSlugs: ['cable-lateral-raise'],
  },
  {
    name: 'Cable Lateral Raise',
    primaryMuscles: ['side_delts'],
    secondaryMuscles: [],
    movementPattern: 'abduction',
    equipmentRequired: ['cable_machine'],
    difficulty: 'beginner',
    type: 'isolation',
    instructions: 'Raise a low cable out to the side with a slight elbow bend.',
    formCues: ['constant tension', 'control the return'],
    contraindications: [],
    substitutionSlugs: ['lateral-raise'],
  },
  {
    name: 'Rear Delt Fly',
    primaryMuscles: ['rear_delts'],
    secondaryMuscles: ['upper_back'],
    movementPattern: 'horizontal_abduction',
    equipmentRequired: ['dumbbell', 'machine'],
    difficulty: 'beginner',
    type: 'isolation',
    instructions: 'Hinge or sit on a reverse fly machine and open the arms wide.',
    formCues: ['thumbs slightly out', 'squeeze rear delts'],
    contraindications: [],
    substitutionSlugs: ['face-pull', 'band-pull-apart'],
  },

  // —— Arms ——
  {
    name: 'Barbell Curl',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    movementPattern: 'elbow_flexion',
    equipmentRequired: ['barbell'],
    difficulty: 'beginner',
    type: 'isolation',
    instructions: 'Curl the bar without swinging the torso, then lower slowly.',
    formCues: ['elbows pinned', 'full extension at bottom'],
    contraindications: ['acute elbow tendinopathy'],
    substitutionSlugs: ['dumbbell-curl', 'cable-curl'],
  },
  {
    name: 'Dumbbell Curl',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    movementPattern: 'elbow_flexion',
    equipmentRequired: ['dumbbell'],
    difficulty: 'beginner',
    type: 'isolation',
    instructions: 'Curl dumbbells together or alternating with controlled tempo.',
    formCues: ['supinate through the lift', 'no shoulder shrug'],
    contraindications: [],
    substitutionSlugs: ['barbell-curl', 'cable-curl'],
  },
  {
    name: 'Cable Curl',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    movementPattern: 'elbow_flexion',
    equipmentRequired: ['cable_machine'],
    difficulty: 'beginner',
    type: 'isolation',
    instructions: 'Curl a straight or EZ bar attachment from a low pulley.',
    formCues: ['constant cable tension', 'soft lockout avoid'],
    contraindications: [],
    substitutionSlugs: ['dumbbell-curl'],
  },
  {
    name: 'Triceps Pushdown',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    movementPattern: 'elbow_extension',
    equipmentRequired: ['cable_machine'],
    difficulty: 'beginner',
    type: 'isolation',
    instructions: 'Push the cable attachment down until elbows are straight, then return.',
    formCues: ['elbows glued to sides', 'only forearms move'],
    contraindications: [],
    substitutionSlugs: ['overhead-triceps-extension', 'bench-dip'],
  },
  {
    name: 'Overhead Triceps Extension',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    movementPattern: 'elbow_extension',
    equipmentRequired: ['dumbbell', 'cable_machine'],
    difficulty: 'beginner',
    type: 'isolation',
    instructions: 'Extend the elbows overhead from a deep stretch behind the head.',
    formCues: ['upper arms still', 'ribs down'],
    contraindications: ['shoulder mobility limits'],
    substitutionSlugs: ['triceps-pushdown'],
  },
  {
    name: 'Bench Dip',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'front_delts'],
    movementPattern: 'elbow_extension',
    equipmentRequired: ['bench', 'bodyweight'],
    difficulty: 'beginner',
    type: 'compound',
    instructions: 'Hands on a bench behind you, lower by bending elbows, then press up.',
    formCues: ['shoulders down', 'limit depth if shoulders complain'],
    contraindications: ['anterior shoulder pain'],
    substitutionSlugs: ['triceps-pushdown'],
  },

  // —— Core / carry ——
  {
    name: 'Plank',
    primaryMuscles: ['core'],
    secondaryMuscles: ['shoulders', 'glutes'],
    movementPattern: 'anti_extension',
    equipmentRequired: ['bodyweight'],
    difficulty: 'beginner',
    type: 'isolation',
    instructions: 'Hold a straight-body plank on forearms or hands without sagging hips.',
    formCues: ['squeeze glutes', 'ribs toward pelvis'],
    contraindications: [],
    substitutionSlugs: ['dead-bug'],
  },
  {
    name: 'Dead Bug',
    primaryMuscles: ['core'],
    secondaryMuscles: [],
    movementPattern: 'anti_extension',
    equipmentRequired: ['bodyweight'],
    difficulty: 'beginner',
    type: 'isolation',
    instructions: 'On your back, extend opposite arm and leg while keeping the low back pressed down.',
    formCues: ['exhale on extension', 'slow tempo'],
    contraindications: [],
    substitutionSlugs: ['plank'],
  },
  {
    name: 'Hanging Knee Raise',
    primaryMuscles: ['core'],
    secondaryMuscles: ['hip_flexors'],
    movementPattern: 'spinal_flexion',
    equipmentRequired: ['pull_up_bar'],
    difficulty: 'intermediate',
    type: 'isolation',
    instructions: 'Hang and raise the knees toward the chest without swinging.',
    formCues: ['posterior tilt at the top', 'control the lower'],
    contraindications: ['shoulder hang pain'],
    substitutionSlugs: ['dead-bug', 'plank'],
  },
  {
    name: 'Farmer Carry',
    primaryMuscles: ['core', 'forearms', 'traps'],
    secondaryMuscles: ['glutes'],
    movementPattern: 'loaded_carry',
    equipmentRequired: ['dumbbell', 'kettlebell'],
    difficulty: 'beginner',
    type: 'compound',
    instructions: 'Walk while holding heavy weights at the sides with a tall posture.',
    formCues: ['pack shoulders', 'short quick steps'],
    contraindications: [],
    substitutionSlugs: ['plank'],
  },
  {
    name: 'Good Morning',
    primaryMuscles: ['hamstrings', 'glutes', 'back'],
    secondaryMuscles: ['core'],
    movementPattern: 'hinge',
    equipmentRequired: ['barbell'],
    difficulty: 'intermediate',
    type: 'compound',
    instructions: 'With the bar on the back, hinge until the torso is near parallel, then stand.',
    formCues: ['soft knees', 'brace hard'],
    contraindications: ['acute low-back pain'],
    substitutionSlugs: ['romanian-deadlift', 'dumbbell-rdl'],
  },
].map((exercise) => ({
  ...exercise,
  slug: slugify(exercise.name),
  isApproved: true,
}));

module.exports = {
  EXERCISE_SEED,
  slugify,
};
